# Generated by Django 2.0.3 on 2020-03-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envheader',
            options={'verbose_name': '请求头配置', 'verbose_name_plural': '请求头配置'},
        ),
    ]
