# Generated by Django 2.0.3 on 2020-03-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200315_1112'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststep',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.RequestData', verbose_name='接口数据'),
            preserve_default=False,
        ),
    ]
