# Generated by Django 2.0.3 on 2020-03-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200315_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststep',
            name='api',
        ),
        migrations.AlterField(
            model_name='teststep',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.RequestData', verbose_name='请求数据'),
        ),
    ]
