# Generated by Django 2.0.3 on 2020-03-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200313_2355'),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('markdown', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
            },
        ),
        migrations.CreateModel(
            name='ApiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '接口组',
                'verbose_name_plural': '接口组',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='data_type',
            field=models.CharField(choices=[('none', '无'), ('form', '表单'), ('json', 'JSON'), ('raw', '原始'), ('multipart', '复合表单'), ('binary', '二进制')], default='none', max_length=15, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='api',
            name='method',
            field=models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE'), ('head', 'HEAD'), ('patch', 'PATCH'), ('options', 'OPTIONS')], default='get', max_length=10, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='api',
            name='path',
            field=models.CharField(default=1, max_length=200, verbose_name='接口路径'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apidoc',
            name='api',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
        ),
        migrations.AddField(
            model_name='api',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.ApiGroup', verbose_name='接口组'),
            preserve_default=False,
        ),
    ]
