# Generated by Django 2.0.3 on 2020-03-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200314_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binarydata',
            options={'verbose_name': '二进制请求数据', 'verbose_name_plural': '二进制请求数据'},
        ),
        migrations.AlterField(
            model_name='binarydata',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.RequestData', verbose_name='请求数据'),
        ),
    ]
