# Generated by Django 2.0.3 on 2020-03-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200314_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='raw',
            field=models.TextField(default=1, verbose_name='请求数据'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.RequestData', verbose_name='请求数据'),
        ),
    ]
