# Generated by Django 2.0.3 on 2020-03-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200314_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdata',
            name='api',
        ),
        migrations.RemoveField(
            model_name='requestdata',
            name='step',
        ),
        migrations.AddField(
            model_name='api',
            name='data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.RequestData', verbose_name='接口数据'),
            preserve_default=False,
        ),
    ]
