# Generated by Django 2.0.3 on 2020-03-15 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200315_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='data',
        ),
        migrations.AddField(
            model_name='requestdata',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
    ]
