# Generated by Django 2.0.3 on 2020-03-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20200315_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonvariable',
            name='data',
        ),
        migrations.DeleteModel(
            name='JSONVariable',
        ),
    ]
