# Generated by Django 2.0.3 on 2020-03-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200315_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarydata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='formvariable',
            name='data',
        ),
        migrations.RemoveField(
            model_name='headervariable',
            name='data',
        ),
        migrations.RemoveField(
            model_name='multipartvariable',
            name='data',
        ),
        migrations.RemoveField(
            model_name='paramvariable',
            name='data',
        ),
        migrations.RemoveField(
            model_name='rawdata',
            name='data',
        ),
        migrations.AddField(
            model_name='binarydata',
            name='api',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formvariable',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headervariable',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipartvariable',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multipartvariable',
            name='value_type',
            field=models.CharField(choices=[('text', '文本'), ('file', '文件')], default='file', max_length=10, verbose_name='变量类型'),
        ),
        migrations.AddField(
            model_name='paramvariable',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawdata',
            name='api',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.Api', verbose_name='接口'),
            preserve_default=False,
        ),
    ]
