# Generated by Django 2.0.3 on 2020-03-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api_test.Tag', verbose_name='标签'),
        ),
    ]
