# Generated by Django 2.0.3 on 2020-03-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20200322_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testreport',
            options={'verbose_name': '测试报告', 'verbose_name_plural': '测试报告'},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': '变量', 'verbose_name_plural': '变量'},
        ),
        migrations.AlterField(
            model_name='env',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name='请求默认配置'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='check',
            field=models.TextField(blank=True, null=True, verbose_name='断言数据'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='extract',
            field=models.TextField(blank=True, null=True, verbose_name='提取数据'),
        ),
    ]
