# Generated by Django 2.0.3 on 2020-03-23 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20200322_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.CharField(default='', max_length=500, verbose_name='描述')),
                ('ip', models.CharField(max_length=100, verbose_name='IP')),
                ('active', models.BooleanField(default=False, verbose_name='活动')),
                ('schedule', models.CharField(max_length=100, verbose_name='执行计划')),
                ('env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_agents', to='api_test.Env', verbose_name='环境')),
            ],
            options={
                'verbose_name': '执行节点',
                'verbose_name_plural': '执行节点',
            },
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='apicategory',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_test.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='agent',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suite_agents', to='api_test.TestSuite', verbose_name='测试套件'),
        ),
    ]
